"""empty message

Revision ID: 5d044b71292e
Revises: 6acead68c213
Create Date: 2022-10-23 19:15:51.963383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d044b71292e'
down_revision = '6acead68c213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'message_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('message_id', sa.INTEGER(), nullable=False))
    op.create_foreign_key(None, 'channels', 'messages', ['message_id'], ['id'])
    # ### end Alembic commands ###
